@extends('layouts.app')
@section('page_title', 'Home')
@section('content')
    @include('components.header')
    @include('components.slider')
    @include('components.banner')
    @include('components.exclusive_products')
    @include('components.single-banner')
    @include('components.featured_products')
    @include('components.testimonial')
    @include('components.shop-info')
    @include('components.newsletter')
    @include('components.footer')
@endsection
